"""The doxBench route harness this leg's route suites ride: a real ephemeral
serve over `opendox.serve.build_server`, the turn and catalog builders, and the
refusal asserter, and nothing else.

A CREATED file: no row in openxFactory's `docs/opendox-carve-manifest.yaml`
(RULED OQ-C — the manifest declares what LEAVES openxFactory, never what a
destination assembles).

WHY IT EXISTS (plan 034 task T040). Three suites at this leg take their harness
from `test_doxbench_routes`: `test_doxbench_knowledge_service.py` and
`test_doxbench_thread_wiring.py` at module scope, and
`test_doxbench_blank_reason.py` inside one test. The module they name is
openxFactory's `tests/ideation-dashboard/test_doxbench_routes.py`, whose manifest
row is `not_moved` (`stays_openxfactory_adapter`), so all three failed on
`No module named 'test_doxbench_routes'` (T005's class C). This module is the
helper of their own that T040 gives them in its place. It is ONE module for all
three, which keeps the reason those suites give for importing the harness rather
than copying it: a second harness is a second set of behaviours to keep in step.

WHAT IT CARRIES, AND FROM WHERE. Exactly the twenty-one names those three
import, plus the definitions those names reach, and no other: of the source
module's 272 top-level statements, 52 are that closure. Each definition is
copied from openxFactory at the carve tag `opendox-carve-0`
(`b075fd91dc8fced8e1373825ba80220c33536bae`), the tree those suites were carved
from, and the changes listed below are the only ones. The section banners are
this module's own. The docstrings travel with their bodies, so where one says
"this module" or "below" it means the source module's tests. openxFactory's own
module is not brought whole: it imports further openxFactory-only modules that
none of these names needs.

WHAT CHANGED IN THE COPY:

  * the carve's `import rewrites` edit class, per module destination row:
    `serve`, `doxbench_hash` and `doxbench_model` are `opendox.X`, and
    `generator` is `openxdox.generator`;
  * the one `path constant`: the served web root was
    `REPO_ROOT / "scripts" / "ideation_dashboard" / "web"`, a pre-carve path
    this leg does not have. It is the PINNED openDox bundle now, through
    `opendox_bundle.web()` (§ 3.4 slice S8), read inside `_serving` per call,
    so a missing bundle is decided for the calling test (`web()`'s docstring);
  * the four wire KINDS. The source took them from `doxbench_contracts`, the
    released contract's reader, which stays in openxFactory (`not_moved`,
    `stays_openxfactory_adapter`), so it is not importable here. They come from
    openDox's own declaration instead, `opendox.serve_wire`'s
    `DOXBENCH_*_KIND` constants. Those are the kinds the routes EMIT, and the
    keys the routes LOOK UP an injected validator by
    (`serve_workbench.py`'s `validators.get(kind)`), so the hermetic fixture
    below serves the route exactly the seam it consults, and no kind is
    re-spelled as a literal here;
  * `released_only`. The released-contract rung needs openxFactory's
    `doxbench_contracts` to read the released bytes, and so does
    `build_server`'s own default validator seam (`serve_wire.py`,
    `default_doxbench_validators`), which is what `_UNSET` selects. This
    checkout carries neither, so the marker skips here, naming why. The source
    decided that from a release root this leg never has.

`_snapshot()` is unchanged, and it is the reason most tests over this harness
need openxFactory's `doc_health`: the fixture snapshot is generated by
`openxdox.generator`, whose own module imports reach `doc_health` (research
R10, `DOC_HEALTH_SURFACE`). That is the declared `doc_health` reach (R1Q6 (d)),
not carve residue, and this harness does not hide it.
"""

from __future__ import annotations

import copy
import http.client
import json
import threading
from contextlib import contextmanager

import pytest

from conftest import BASE_REPO, PINNED_REVISION, FakeGit

from jsonschema import Draft202012Validator

import opendox_bundle

from opendox import serve as serve_mod
from opendox import serve_wire
from opendox.doxbench_hash import content_identity
from opendox.doxbench_model import (
    FakeWorkbenchModelPort,
    ModelCatalog,
    ModelCatalogEntry,
)
from openxdox.generator import generate_snapshot


def _snapshot():
    return generate_snapshot(
        BASE_REPO, "fixture-repo", source_revision=PINNED_REVISION, git=FakeGit())


# ============================================================================
# injected validators, fixtured to the envelope DISCRIMINATORS only
#
# The routes validate every wire shape they emit -- and the chat request they
# accept -- through an INJECTED seam, exactly like `model_port_factory`. The
# fixtures pin `schema_version`, the instance `kind`, the required-key list and
# closedness, and restate NO value-level rule: those are the release's, and a
# fixture restating one would be a second contract authority.
# ============================================================================

_FIXTURE_CATALOG_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "required": ["schema_version", "kind", "models"],
    "properties": {
        "schema_version": {"const": 1},
        "kind": {"const": serve_wire.DOXBENCH_MODEL_CATALOG_KIND},
        "models": {"type": "array"},
    },
}

# THE ONE SERVED TURN FAMILY, fixtured to discriminators and closedness only.
#
# Three v1 fixture schemas stood above these until contract-v3.0
# (retire-doxbench-chat-turn-v1) and are gone with the envelopes they mirrored.
# They are not merely unused here: `_FIXTURE_SCHEMAS` is what the injected
# validator seam serves, and `_doxbench_wire_conforms` treats an absent
# validator for a kind as FALSE — so a fixture that still carried the v1 kinds
# would let this suite bless a shape the release no longer defines, which is
# exactly the forking of contract authority the header above refuses.
#
# `bound_buffer` is where v1 carried `active_document_path`: the binding is
# DECLARED, not inferred from an adjacent field, and the record carries that key
# plus the selected-model metadata.
_FIXTURE_TURN_V2_REQUEST_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "required": ["schema_version", "kind", "client_turn_id", "scope",
                 "bound_buffer", "working_subject", "message", "model_id",
                 "last_assistant_turn_id", "transcript", "buffers"],
    "properties": {
        "schema_version": {"const": 1},
        "kind": {"const": serve_wire.DOXBENCH_CHAT_TURN_V2_KIND},
        "client_turn_id": {},
        "scope": {},
        "bound_buffer": {},
        "working_subject": {},
        "message": {},
        "model_id": {},
        "last_assistant_turn_id": {},
        "transcript": {},
        "buffers": {},
    },
}

_FIXTURE_TURN_V2_SUCCESS_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "required": ["schema_version", "kind", "client_turn_id", "assistant_turn_id",
                 "model_id", "selected_model", "bound_buffer", "observed_hashes",
                 "assistant_prose", "proposals"],
    "properties": {
        "schema_version": {"const": 1},
        "kind": {"const": serve_wire.DOXBENCH_CHAT_TURN_V2_SUCCESS_KIND},
        "client_turn_id": {}, "assistant_turn_id": {}, "model_id": {},
        "selected_model": {}, "bound_buffer": {},
        "observed_hashes": {}, "assistant_prose": {}, "proposals": {},
        # contract-v1.40 (task 10.7). DECLARED HERE AND NOT REQUIRED, which
        # mirrors the release exactly: the key is optional on the wire, and this
        # fixture's whole job is discriminators and CLOSEDNESS — the released
        # bytes hold the posture's value rules, and a test over those bytes is
        # what checks them (`test_doxbench_contracts`). A fixture that restated
        # them would be a second contract authority, which is the thing this
        # fixture's own header refuses to be.
        "context_packet": {},
    },
}

_FIXTURE_TURN_V2_FAILURE_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "required": ["schema_version", "kind", "client_turn_id", "error", "message"],
    "properties": {
        "schema_version": {"const": 1},
        "kind": {"const": serve_wire.DOXBENCH_CHAT_TURN_V2_FAILURE_KIND},
        "client_turn_id": {}, "error": {}, "message": {},
        "limit": {},
    },
}

_FIXTURE_SCHEMAS = {
    serve_wire.DOXBENCH_MODEL_CATALOG_KIND: _FIXTURE_CATALOG_SCHEMA,
    serve_wire.DOXBENCH_CHAT_TURN_V2_KIND: _FIXTURE_TURN_V2_REQUEST_SCHEMA,
    serve_wire.DOXBENCH_CHAT_TURN_V2_SUCCESS_KIND: _FIXTURE_TURN_V2_SUCCESS_SCHEMA,
    serve_wire.DOXBENCH_CHAT_TURN_V2_FAILURE_KIND: _FIXTURE_TURN_V2_FAILURE_SCHEMA,
}


def _fixture_validators():
    return {kind: Draft202012Validator(schema)
            for kind, schema in _FIXTURE_SCHEMAS.items()}


# `_serving` injects fixture validators by default; this sentinel asks it to
# pass NOTHING, so `build_server`'s own default seam is what binds.
_UNSET = object()


# ============================================================================
# the shared HTTP harness: `_serving`/`_handler_class`/`_request`/
# `_capabilities`/`_console_headers`
# ============================================================================

@contextmanager
def _serving(tmp_path, *, actor="brett", checkout_root=None,
            model_port_factory=None, snapshot=None,
            knowledge_declaration=None, packet_assembler=None,
            schema_validator_factory=_fixture_validators):
    """PIN EVOLUTION (T024/T050/T051 wire clause): the harness now injects
    released-schema validators, because the routes validate every wire shape
    they emit and the request they accept. The default is the hand-held
    fixture factory above, so this suite stays hermetic -- it must never
    depend on a pinned openxFactory checkout being present. Pass `_UNSET` to
    exercise `build_server`'s own default seam instead."""
    snap_path = tmp_path / "snapshot.json"
    snap_path.write_text(json.dumps(snapshot or _snapshot()), encoding="utf-8")
    extra = ({} if schema_validator_factory is _UNSET
             else {"schema_validator_factory": schema_validator_factory})
    httpd = serve_mod.build_server(
        opendox_bundle.web(),
        snap_path,
        checkout_root if checkout_root is not None else BASE_REPO,
        head=PINNED_REVISION,
        actor=actor,
        model_port_factory=model_port_factory,
        # add-doxbench-editing-phase-b task 10.6: the INSTALL-TIME retrieval
        # backend declaration. `None` -- the default here and in
        # `build_server` -- is the declared reduced-packet posture, which is
        # what every pre-existing test in this file exercises unchanged.
        knowledge_declaration=knowledge_declaration,
        # The packet assembler is a COLLABORATOR of the turn route, injected
        # like every other one; `None` keeps `build_server`'s real default.
        packet_assembler=packet_assembler,
        **extra,
    )
    thread = threading.Thread(target=httpd.serve_forever, daemon=True)
    thread.start()
    host, port = httpd.server_address[:2]
    try:
        yield httpd, host, port
    finally:
        httpd.shutdown()
        httpd.server_close()
        thread.join(timeout=2)


def _handler_class(httpd):
    """The bound `DashboardHandler` subclass a server was built with -- the
    same unwrap `test_doxbench_request_handling.py`/`test_session_snapshot.py`
    use, since `build_server` hands `ThreadingHTTPServer` a
    `functools.partial(bound, directory=...)`."""
    return getattr(httpd.RequestHandlerClass, "func", httpd.RequestHandlerClass)


def _request(host, port, method, path, *, body=None, headers=None):
    """Unlike the T024 file's 2-tuple twin, this also returns the response
    HEADERS (lower-cased, mirroring test_doxbench_transport.py's own
    `resp.getheaders()` idiom) and the RAW response bytes, since this route's
    JSON-media-type and zero-leakage assertions need both. `payload` is `None`
    on a non-JSON body (e.g. the static-file 404 page a near-miss path still
    falls through to) rather than raising."""
    conn = http.client.HTTPConnection(host, port, timeout=5)
    raw_request_body = None if body is None else json.dumps(body)
    conn.request(method, path, body=raw_request_body, headers=headers or {})
    resp = conn.getresponse()
    raw_response_body = resp.read()
    try:
        payload = json.loads(raw_response_body.decode("utf-8") or "{}")
    except ValueError:
        payload = None
    response_headers = {k.lower(): v for k, v in resp.getheaders()}
    conn.close()
    return resp.status, payload, response_headers, raw_response_body


def _capabilities(host, port):
    status, payload, _headers, _raw = _request(host, port, "GET", "/capabilities")
    assert status == 200
    return payload


def _console_headers(caps):
    return {
        "Content-Type": "application/json",
        "X-XF-Console-Token": caps["console_token"],
    }


# ============================================================================
# the chat-turn route: the turn body, the catalog and port, the POST, and the
# refusal asserter
# ============================================================================

OUTLINE_PATH = "ideation/staging/ideation-governance/README.md"
CHAT_ROUTE = serve_mod.ACTIONS_WORKBENCH_CHAT_TURN_ROUTE

_S_OUTLINE = "SENTINEL-OUTLINE-BUFFER-TEXT-a91f"
_S_DOCUMENT = "SENTINEL-DOCUMENT-BUFFER-TEXT-b72e"
_S_SUBJECT = "SENTINEL-WORKING-SUBJECT-c53d"
_S_MESSAGE = "SENTINEL-HUMAN-MESSAGE-d14c"
_S_TRANSCRIPT = "SENTINEL-TRANSCRIPT-TEXT-e65b"
_TURN_SENTINELS = (_S_OUTLINE, _S_DOCUMENT, _S_SUBJECT, _S_MESSAGE, _S_TRANSCRIPT)


def _buf(kind, path, content, *, repository="fixture-repo", base_ref="main",
         base_revision=PINNED_REVISION, base_hash=None, content_hash=None, dirty=True):
    """One buffer envelope. Hashes are computed from `content` unless overridden."""
    digest = content_identity(content).hex
    return {"kind": kind, "repository": repository, "path": path,
            "base_ref": base_ref, "base_revision": base_revision,
            "base_hash": base_hash if base_hash is not None else digest,
            "content_hash": content_hash if content_hash is not None else digest,
            "content": content, "dirty": dirty}


def _turn(**over):
    """A structurally valid turn body whose document buffer is the
    not-yet-created (null path) carve-out, so the only in-scope editable path
    used is the outline README.

    RE-EXPRESSED IN THE SURVIVING FAMILY at contract-v3.0
    (retire-doxbench-chat-turn-v1). This built a `workbench-chat-turn` request
    until the v1 envelopes were removed; every test in this module that posts a
    turn goes through it, so the whole route surface below now exercises the one
    family the release defines. Two fields moved and nothing else did: the
    `kind`, and `active_document_path: None` becoming `bound_buffer: "outline"`
    — the SAME turn, whose binding is now DECLARED rather than inferred from the
    absence of a document path. The buffer set is unchanged, so the assertions
    that read it are unchanged too."""
    body = {
        # PIN EVOLUTION (T051 wire clause): the RELEASED request envelope is
        # closed and requires both discriminators, so the fixture carries them.
        # Every other field is unchanged, and no assertion below was relaxed.
        "schema_version": 1,
        "kind": serve_wire.DOXBENCH_CHAT_TURN_V2_KIND,
        "client_turn_id": "turn-0001",
        "scope": {"repository": "fixture-repo", "ref": "main",
                  "tile_kind": "staged", "tile_id": "ideation-governance"},
        "bound_buffer": "outline",
        "working_subject": "Clarify the acceptance boundary " + _S_SUBJECT,
        "message": "Which open question should we close next? " + _S_MESSAGE,
        "model_id": "model-a",
        "last_assistant_turn_id": None,
        "transcript": [],
        "buffers": [
            _buf("outline", OUTLINE_PATH, "# Outline\n\n" + _S_OUTLINE),
            _buf("document", None, "# Document\n\n" + _S_DOCUMENT),
        ],
    }
    body.update(over)
    return body


def _catalog(*, model_id="model-a", available=True, input_limit_bytes=1_048_576):
    return ModelCatalog((ModelCatalogEntry(
        model_id=model_id, label="Approved authoring model",
        provider_class="on-tenant", available=available,
        input_limit_bytes=input_limit_bytes, output_limit_bytes=900_000,
        data_handling="Processed in the approved tenant boundary"),))


def _port(catalog=None):
    return FakeWorkbenchModelPort(catalog if catalog is not None else _catalog())


def _post_turn(tmp_path, body, *, port=None, headers=None, snapshot=None,
               knowledge_declaration=None, inspect_handler=None,
               packet_assembler=None, checkout_root=None,
               schema_validator_factory=_fixture_validators):
    """POST a turn as the real local console. Returns (status, payload, port).

    `inspect_handler` is called with the bound handler class while the server
    is still up, for a test that needs to read per-process state the response
    does not carry (the usage meter, task 10.8).

    `schema_validator_factory` defaults to the hermetic fixture, exactly as
    `_serving` does; the released-schema tests pass `_require_released_validators`
    output so a value-level rule can be exercised as the release states it."""
    fake = port if port is not None else _port()
    with _serving(tmp_path, model_port_factory=(lambda: fake), snapshot=snapshot,
                  knowledge_declaration=knowledge_declaration,
                  packet_assembler=packet_assembler,
                  schema_validator_factory=schema_validator_factory,
                  checkout_root=checkout_root) as (httpd, host, prt):
        caps = _capabilities(host, prt)
        status, payload, _headers, _raw = _request(host, prt, "POST", CHAT_ROUTE, body=body,
                                   headers=headers or _console_headers(caps))
        if inspect_handler is not None:
            inspect_handler(_handler_class(httpd))
    return status, payload, fake


def _assert_refusal(status, payload, code, message=None):
    """PIN EVOLUTION (T051 wire clause). Every refusal reached AFTER the turn
    identity has been read and found wire-valid now carries the RELEASED
    `workbench-chat-turn-v2-failure` envelope, which is CLOSED and admits no
    `ok` key -- so the `ok is False` assertion this helper used to make is now
    the wrong pin, not a weakened one. The code and the fixed module-level
    message are asserted exactly as before, and the key set is asserted EXACTLY,
    so nothing can be added to a failure body unnoticed.

    ONE ASSERTER, since contract-v3.0 (retire-doxbench-chat-turn-v1). A
    `_assert_v2_refusal` twin stood beside this while two families were served
    and differed from it in exactly one clause, the `kind`: a refusal is
    answered in the family its request arrived in, and asserting the wrong one
    passed only for a route that answered the wrong one. One family survives, so
    the distinction it drew no longer exists and its call sites came here.

    `client_turn_id` is asserted present and in the released 1..128 bound
    rather than compared to a literal, because callers below use several turn
    ids; the exact ECHO is pinned by its own dedicated test.

    Refusals reached BEFORE the request validated -- the plane gate, the
    console gate, and the route-specific body bound -- keep the pre-existing
    fixed shape and are asserted by `_assert_preidentity_refusal`."""
    assert status == serve_mod.doxbench_error_status(code)
    expected = {"schema_version", "kind", "client_turn_id", "error", "message"}
    if code == serve_mod.DOXBENCH_ERR_REQUEST_LIMIT_EXCEEDED:
        expected.add("limit")
    assert set(payload) == expected
    assert payload["schema_version"] == 1
    assert payload["kind"] == serve_wire.DOXBENCH_CHAT_TURN_V2_FAILURE_KIND
    assert isinstance(payload["client_turn_id"], str)
    assert 1 <= len(payload["client_turn_id"]) <= 128
    assert payload["error"] == code
    assert payload["message"] == _expected_refusal_message(code, message)


def _expected_refusal_message(code, message):
    """The message a refusal must carry: the catalog's, unless a caller names a
    different FIXED module-level constant.

    `None` is the default at every one of the ~30 call sites below, and that is
    the point of the parameter rather than a convenience: those call sites now
    assert positively that their violation still gets the GENERIC sentence, so
    the one cause-naming message added for the buffers floor cannot leak into
    any other refusal without failing here."""
    if message is None:
        return serve_mod.DOXBENCH_ERROR_CATALOG[code][1]
    return message


# ============================================================================
# the released-contract rung: skipped in this checkout
#
# It needs openxFactory's `doxbench_contracts` (the source module's
# `_RELEASED_ROOT` resolved a release checkout through it), and so does
# `build_server`'s own default validator seam, which `_UNSET` selects. Neither
# arrives at this leg or with its pinned openDox, so the rung cannot run here,
# and the skip says so rather than letting it fail on a module this leg does
# not carry.
# ============================================================================

released_only = pytest.mark.skip(
    reason=("the released-contract integration rung needs openxFactory's "
            "doxbench_contracts (carve manifest: not_moved, "
            "stays_openxfactory_adapter), which this checkout does not carry"),
)


# ============================================================================
# the T051 dispatch arm's catalog-only adapter
# ============================================================================

class _CatalogOnlyPort:
    """The pre-T049 adapter surface: `timeout_seconds` + `catalog()` and NO
    dispatch member. T049 widened the PROTOCOL and the fake, so the
    refused-by-absence posture needs this explicit catalog-only adapter to
    stay testable -- it is the exact shape a deployment without an approved
    dispatch adapter presents."""

    timeout_seconds = 30.0

    def __init__(self, catalog=None):
        self._catalog = catalog if catalog is not None else _catalog()
        self.calls = []

    def catalog(self):
        self.calls.append("catalog")
        return self._catalog


# ============================================================================
# the widened turn envelope: its turn-id namespace, and the fixture snapshot
# with documents added to the tile's own material
# ============================================================================

def _turn_v2(**over):
    """`_turn()` under this section's own turn-id namespace.

    It carried its own copy of the envelope while two families were served, so
    that the widened lane could be exercised against a `_turn()` that built the
    deprecated one. `_turn()` builds this envelope itself since contract-v3.0
    (retire-doxbench-chat-turn-v1), and a second literal would be a second thing
    to keep in step with the release for no remaining reason.

    THE NAME AND THE DEFAULT ID STAY. Several tests in this section post two
    turns to one server and rely on the `turn-v2-…` ids being distinct from the
    `turn-0001` the rest of the module uses, and one of them asserts the echoed
    id verbatim; sharing a default across the file would silently turn those
    into idempotent replays of each other."""
    over.setdefault("client_turn_id", "turn-v2-0001")
    return _turn(**over)


def _staged_document(path):
    return {
        "id": path, "path": path, "stage": "staged", "kind": "staging-packet",
        "summary": "fixture document for the widened-lane tests",
        "topics": ["ideation-governance"],
        "dates": {"captured": "2026-08-18"},
        "destinations": {"staged_topics": ["ideation-governance"]},
        "completeness": {
            "score": 0.6,
            "structure": {"value": 1.0, "count": 3},
            "length": {"value": 1.0, "count": 45},
            "open_markers": {"value": 1.0, "count": 0},
            "keyword_coverage": {"value": 1.0, "count": 1},
            "link_degree": {"value": 1.0, "count": 2},
        },
    }


def _snapshot_with_editable(*paths):
    """The fixture snapshot with `paths` added to the tile's OWN material, so the
    scope authority resolves each one as in-scope AND editable."""
    snapshot = copy.deepcopy(_snapshot())
    snapshot["documents"] = list(snapshot["documents"]) + [
        _staged_document(path) for path in paths]
    for topic in snapshot["staged_topics"]:
        if topic.get("staging_id") == "ideation-governance":
            topic["files"] = list(topic["files"]) + list(paths)
    return snapshot


DOC_ALPHA = "ideation/staging/ideation-governance/alpha.md"
DOC_ZULU = "ideation/staging/ideation-governance/zulu.md"
